version: "3.8"

services:
  test-postgres:
    image: postgres:latest
    container_name: test-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      # 호스트 포트를 6432로 변경했습니다. (호스트:컨테이너)
      - "6432:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql
    networks:
      - services

volumes:
  test_postgres_data:
    name: test_postgres_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/docker-storage/test-postgres/data

networks:
  services:
    external: true