_format_version: "3.0"
_transform: true

# -------------------------------------------------------------------------
# 🔗 SERVICES & ROUTES
# -------------------------------------------------------------------------
services:
  - name: user-service
    url: http://jenkins:8080
    routes:
      - name: user-public-route
        paths:
          - /api/v1/users
        strip_path: false

  - name: payment-service
    url: http://mattermost:8065
    routes:
      - name: payment-route
        paths:
          - /api/v1/payments
        strip_path: false


# -------------------------------------------------------------------------
# 🔌 PLUGINS
# -------------------------------------------------------------------------
plugins:

  # 글로벌 CORS
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
        - X-Requested-With
      exposed_headers:
        - X-Total-Count
      credentials: true
      max_age: 3600

  # user-service Rate Limit
  - name: rate-limiting
    service: user-service
    config:
      minute: 100
      hour: 5000
      policy: local

  # payment JWT
  - name: jwt
    route: payment-route
    config:
      header_names:
        - authorization
      claims_to_verify:
        - exp

  # Prometheus Metrics
  - name: prometheus