version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    hostname: prometheus.smartseoapp.com
    ports:
      - "9090:9090"
    volumes:
      # 💡 중요: 프로메테우스 설정 파일을 호스트에서 직접 수정할 수 있도록 바인드
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # 메트릭 데이터 영구 저장 공간
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - services

volumes:
  prometheus_data:
    name: prometheus_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/docker-storage/prometheus/data

networks:
  services:
    external: true