services:
  certbot:
    image: certbot/certbot
    container_name: certbot

    volumes:
      - /storage/docker-storage/certbot/conf:/etc/letsencrypt
      - /storage/docker-storage/certbot/www:/var/www/certbot

    networks:
      - services

networks:
  services:
    external: true