version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped
    hostname: gitlab.smartseoapp.com

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.smartseoapp.com'

        gitlab_rails['gitlab_shell_ssh_port'] = 2222

        # SSL은 외부 프록시(NPM/Nginx) 처리
        nginx['listen_port'] = 80
        nginx['listen_https'] = false

        # 프록시 뒤에서 HTTPS 인식
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

        letsencrypt['enable'] = false

    ports:
      - "8081:80"
      - "2222:22"

    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

    shm_size: "256m"

    networks:
      - services

volumes:
  gitlab_config:
    name: gitlab_config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/docker-storage/gitlab/config

  gitlab_logs:
    name: gitlab_logs
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/docker-storage/gitlab/logs

  gitlab_data:
    name: gitlab_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/docker-storage/gitlab/data

networks:
  services:
    external: true